### ISSUE TITLE
Issues with lavender

### ISSUE THREAD

**Issue by ernestdefoe** [NodeBB/nodebb-theme-lavender#83]
This is in reference to this post.

https://community.nodebb.org/topic/10693/issues-with-lavender-theme

**Comment by lots0logs** [comment]
The first issue you mentioned isn't a bug AFAIK, Lavender has never provided the Edit Profile and Settings links in that dropdown menu. Instead, you simply click on the user name. The second issue you described was caused by a bug in lavender's parent theme that was fixed yesterday. Make sure you have installed the latest version.

**Comment by lots0logs** [comment]
This is the only remaining issue that I'm seeing on our forum after updating to 1.5 and rebasing our lavender child theme on the latest version:

![2017-05-17_12-23-58-am](https://cloud.githubusercontent.com/assets/4675662/26139574/534825a2-3a97-11e7-86de-0527941356dd.png)

**Comment by ernestdefoe** [comment]
I'm new to NodeBB so could you please explain to me how to update the parent theme please?

**Comment by ernestdefoe** [comment]
Nevermind I figured out how to do it and yes it fixed the issue with the more button. Now I can edit my profile.
